from model.scn import Loc_SCN
from model.triangulation import AlgebraicTriangulationNet,VolumetricTriangulationNet,AlgResNet,VolResNet,AlgAdafuseNet,Vol3dResNet
from model.pose_resnet import get_pose_net
from model.adafuse_network import AdafuseNet